# Generated by Django 5.2.4 on 2025-07-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_approved',
        ),
    ]
