# Generated by Django 5.2.4 on 2025-07-24 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('working_hours', models.TextField(help_text='Describe weekly availability (e.g., Mon-Fri 9am-5pm)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
