# Generated by Django 5.2.4 on 2025-07-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_workinghour_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghour',
            options={},
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
