# Generated by Django 5.2.4 on 2025-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_workinghour_options_alter_workinghour_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
